brush_type: ellipse
gradient_smoothing_radius: 20
gradient_smoothing_type: bilateral
gradient_type: sharr
img_path: ../_demo/images/img.png
img_save_path: sbr/ellipse/17.jpg
length: base
length_first_flag: true
length_scale: 0.5
palette_size: 10
preset_save_path: ../configs/presets/sbr/ellipse/17.yaml
smoothing_iterations: 3
stroke_scale: 1
