brush_type: ellipse
gradient_smoothing_radius: 10
gradient_smoothing_type: gaussian
gradient_type: sharr
img_path: ../_demo/images/img.png
img_save_path: sbr/ellipse/28.jpg
length: inverse
length_first_flag: false
length_scale: 3
palette_size: 10
preset_save_path: ../configs/presets/sbr/ellipse/28.yaml
smoothing_iterations: 1
stroke_scale: 2
