brush_type: ellipse
gradient_smoothing_radius: 10
gradient_smoothing_type: gaussian
gradient_type: sharr
img_path: ../_demo/images/img.png
img_save_path: sbr/ellipse/32.jpg
length: base
length_first_flag: true
length_scale: 0.3333333333333333
palette_size: 10
preset_save_path: ../configs/presets/sbr/ellipse/32.yaml
smoothing_iterations: 1
stroke_scale: 1
