brush_type: ellipse
gradient_smoothing_radius: 20
gradient_smoothing_type: gaussian
gradient_type: sharr
grayscale: true
grid_scale: 2
has_cardboard: false
img_path: ../_demo/images/img.png
img_save_path: sbr/ellipse/57.jpg
length: base
length_first_flag: true
length_scale: 0.3333333333333333
palette_size: 10
preset_save_path: ../configs/presets/sbr/ellipse/57.yaml
smoothing_iterations: 1
stroke_scale: 1
