brush_type: ellipse
gradient_smoothing_radius: 20
gradient_smoothing_type: gaussian
gradient_type: sharr
img_path: ../_demo/images/img.png
img_save_path: sbr/ellipse/7.jpg
length: base
length_first_flag: true
length_scale: 2
palette_size: 10
preset_save_path: ../configs/presets/sbr/ellipse/7.yaml
stroke_scale: 1
