brush_type: circle
gradient_smoothing_radius: 0
img_path: ../_demo/images/img.png
img_save_path: sbr/circle/0.jpg
length: base
palette_size: 10
preset_save_path: ../configs/presets/sbr/circle/0.yaml
stroke_scale: 0
length_first_flag: true
