brush_type: circle
gradient_smoothing_radius: 20
img_path: ../_demo/images/img.png
img_save_path: sbr/circle/32.jpg
length: base
length_first_flag: true
length_scale: 0.3333333333333333
palette_size: 10
preset_save_path: ../configs/presets/sbr/circle/32.yaml
stroke_scale: 1
